- name: Template a file to /etc/my.cnf.d
  template:
    src: "{{config_file}}"
    dest: "{{cnf_dest}}/my-custom.cnf"
  register: template_cnf

- name: confirm dest of config file
  debug:
    msg: successfully uploaded
  when: template_cnf.dest == "/etc/my.cnf.d/my-custom.cnf"