# - name: Call config Tasks
#   import_tasks: config.yml

- name: Copy over DB
  synchronize:
    src: {{ db_file }}
    dest: /tmp

- name: Compress file using BZ2
  archive:
    path: /tmp/{{ db_file }}
    dest: /tmp/{{ db_file }}.bz2
    format: bz2

- name: Create Wordpress DB
  mysql_db:
    name: wordpress
    state: import
    target: /tmp/{{ db_file }}.bz2
  # notify:
  # - Load data in MariaDB