# - name: Call config Tasks
#   import_tasks: config.yml

- name: Copy over DB
  synchronize:
    src: dump.sql
    dest: /tmp

- name: Create Wordpress DB
  mysql_db:
    name: wordpress
    state: import
    target: /tmp/dump.sql