# - name: Call config Tasks
#   import_tasks: config.yml

- name: Copy over DB
  synchronize:
    src: employees_db-full-1.0.6.tar.bz2
    dest: /tmp

- name: Create Wordpress DB
  mysql_db:
    name: wordpress
    state: import
    target: /tmp/employees_db-full-1.0.6.tar.bz2