- name: Delete database with name 'wordpress'
  mysql_db:
    name: wordpress
    state: absent

# - name: Call config Tasks
#   import_tasks: config.yml

- name: Copy over DB
  synchronize:
    src: "{{ db_file }}"
    dest: /tmp
  
- name: Create Wordpress DB
  mysql_db:
    name: wordpress
    state: import
    target: /tmp/{{ db_file }}