# - name: Call config Tasks
#   import_tasks: config.yml

- name: Copy over DB
  synchronize:
    src: "{{ item }}"
    dest: /tmp/hr-db/
  with_items:
    - "{{ db_file }}"
    # - "{{ db_data }}"

- name: Compress file using BZ2
  archive:
    path: /tmp/hr-db/*
    dest: /tmp/hr-db/{{ database }}.bz2
    format: bz2

- name: Create Wordpress DB
  mysql_db:
    name: wordpress
    state: import
    target: /tmp/hr-db/dump.sql.bz2
  # notify:
  # - Load data in MariaDB