- name: Install php
  yum:
    name: php
    state: present

- name: Install Mariadb Server
  yum:
    name: mariadb-server
    state: present

- name: Start Mariadb
  service:
    name: mariadb
    enabled: yes
    state: started
  notify: Populate service facts