- name: Install php
  yum:
    name: php
    state: present

- name: Install Mariadb Server
  yum:
    name: mariadb-server
    state: present

- name: Install Python3-PyMySQL
  yum:
    name: python2-PyMySQL
    state: present
  # notify:
  # - Load data in MariaDB
    
- name: Start Mariadb
  service:
    name: mariadb
    enabled: yes # service starts on boot
    state: started
  notify: 
  - Populate service facts
  - Print Mariadb status